# Generated by Django 2.1.4 on 2018-12-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rants', '0001_add_rant_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='rant',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
